### ISSUE TITLE
SFC main dependencies to mqtt-target component that don`t exist

### ISSUE THREAD

**Issue by lucian-pruteanu** [aws-samples/shopfloor-connectivity#17]
Step to reproduse:
-No greengrass components deployed with previous versions of SFC
-Using the latest version 1.1.7
-Install the greengrass components of SFC using release version with cdk
-Look into dependencies of the SFC-main component and see 4, one is com.amazon.sfc.aws-iot-mqtt-target

Expected behavior:
com.amazon.sfc.aws-iot-mqtt-target is present as component in aws

Observed behavior:
com.amazon.sfc.aws-iot-mqtt-target is missing. This also lead to error in trying to deploy the sfc-main as it is not finding the component.

I test out in 1.0.8, the component is there. 

The new naming of the component is com.amazon.sfc.mqtt-target?

**Comment by arieleeuw** [comment]
This is correct.
There are two MQTT targets:

- **aws-iot-core-target** (factory className com.amazonaws.sfc.awsiotcore.AwsIotCoreTargetWriter) which uses the AWS IoT service API for submitting data and and X509 certificates/IAM to get permisson to make the service calls. This one replaces the aws-iot-http-target.
- **mqtt-target** (factory classname com.amazonaws.sfc.mqtt.MqttTargetWriter) which is generic MQTT target using the eclipse paho client. This one replaced the aws-iot-mqtt-target.

Both adapters have been upgraded to use batching (message size/message count/interval) and the option to use compression.

Thanks for informing us, we'll update the dependencies in the example.

**Comment by asamerh4** [comment]
Hello Lucian, thanks for raising that! Have pushed a fix for the SFC Greengrass demo recipes. Note: The recipe for sfc-main is just an example, with some sfc-modules included. Typically one does create a custom sfc-main recipe (with custom dependencies) to match a specific environment.

**Comment by asamerh4** [comment]
fixed in latest commit
