### ISSUE TITLE
[Feature Request] Improve interval debug messages

### ISSUE THREAD

**Issue by qoomon** [aws-samples/shopfloor-connectivity#19]
Currently interval debug messages are not containing any information about the interval e.g. scheduler.

example message `Read cycle took 5.107901997s, which is more than read interval of 1s.`

I'd be glad if these warning messages get extended by context information to be able to debug the root cause.

And thx again for this awesome project.

**Comment by arieleeuw** [comment]
Thanks, good feedback!

The warning which is currently based on the total duration of the parallel reads of all sources use by the schedule.

In a next release we'll add:

- an extra measurement for the duration for a read for every individual  source and output a warning if this one is longer than the interval.
- the duration to the trace output message : "Finished reading from source \"< sourcename >\", read [succeeded|failed] **and took < duration **>****

Will this work for you?

**Comment by qoomon** [comment]
Actually I'd like to see the scheduler name in the log message, because I have multiple schedules on the same source.

**Comment by arieleeuw** [comment]
Just added the code. will look like this

```
2024-07-29 16:09:48.586 WARNING- Reading from  source "OPCUASOURCE" took 1.097s, which is more than the schedule read interval of 1s
2024-07-29 16:09:48.587 WARNING- Read cycle took 1.098090s, which is more than read interval of 1s
```

**Comment by arieleeuw** [comment]
Hi,

We've added the schedule name as well to the message.

```
2024-07-30 09:33:21.120 WARNING- Reading from  source "OPCUASOURCE" took 19.221s, which is more than the read interval of 1s for schedule "TestSchedule"
2024-07-30 09:33:21.122 WARNING- Read cycle took 19.23s, which is more than read interval of 1s  for schedule "TestSchedule"
```

The first warning if for reading for (each) individual source for which the reading takes more than the interval of the schedule.
The second one is for the total time it took for reading from all sources. Reading of these are done in parallel and do overlap. The max number of sources that are read in parallel is 5. This number can be tuned with the "MaxConcurrentSourceReaders" setting in the optional "Tuning" section at the root of the configuration.

**Comment by arieleeuw** [comment]
Implemented in V1.3.1

**Comment by qoomon** [comment]
@arieleeuw  Thank you very much

**Comment by qoomon** [comment]
just a minor finding there is a double space between from and source "Reading from  source"

**Comment by qoomon** [comment]
The log output is helping a lot thanks a gain
