### ISSUE TITLE
MQTT-Adapter only fetches last message on interval 

### ISSUE THREAD

**Issue by fwerkmeister** [aws-samples/shopfloor-connectivity#25]
We are using the **MQTT-Adapter** to fetch messages from an EMQX broker deployed with AWS Greengrass. We have multiple clients that send messages to the broker. We are processing the messages using shopfloor-connectivity-framework and forward them to IOT-Core using the **AWS-IOT-Core** Target Type.  

With a higher number of message we recognised that not all messages are arriving on IOT-Core. We discovered that this is due to the Interval set within the schedule. Obviously only the last message is fetched when the interval timer fires. Also setting the interval to a minimum of couple 100 milliseconds, there are still messages that get lost. 

For our use case it is crucial that all messages arriving at the MQTT broker are fetched by the shopfloor-connectivity-framework. It would be a good improvement for us to adapt the MQTT-Adapter so that no messages get lost.    

Currently we are using **version 1.4.1**

**Comment by asamerh4** [comment]
Thanks Felix for raising that - we're looking into that asap.

**Comment by arieleeuw** [comment]
Currently the adapter acts in keep-last mode, we can add an option to switch to keep-all mode in which case the received values over a read interval are returned as a list value.

**Comment by fwerkmeister** [comment]
That would be a helpful feature for MQTT. Otherwise it would be possible to ensure that all messages have been processed. Thanks for that.

**Comment by arieleeuw** [comment]
Version v1.5.2

Added **ReadMode** setting to MQTT Target adapter configuration. Set to value **"KeepAll"** to collect all received messages in a read interval.

```
 "MqttAdapter": {
    "AdapterType": "MQTT",
    "ReadMode" : "KeepAll",
    "Brokers": {
      "MQTT-BROKER": {
        "EndPoint" : "tcp://test.mosquitto.org",
        "Port" : 1883
      }
    }
  },
```
